project_001:
  outputs:
    dev:
      catalog: hive_metastore
      host: '{{ env_var(''DATABRICKS_HOST'') }}'
      http_path: '{{ env_var(''DATABRICKS_HTTP_PATH'') }}'
      schema: dbt_jesse_dev
      threads: 2
      token: '{{ env_var(''DATABRICKS_PAT'') }}'
      type: databricks
    stg:
      catalog: hive_metastore
      host: '{{ env_var(''DATABRICKS_HOST'') }}'
      http_path: '{{ env_var(''DATABRICKS_HTTP_PATH'') }}'
      schema: dbt_jesse_stg
      threads: 2
      token: '{{ env_var(''DATABRICKS_PAT'') }}'
      type: databricks
  target: dev
project_002:
  outputs:
    dev:
      catalog: hive_metastore
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      schema: dbt_jesse_dev
      threads: 1
      token: "{{ env_var('DATABRICKS_PAT') }}"
      type: databricks
  target: dev
