SELECT
    ID,
    ORDERID AS ORDER_ID,
    PAYMENTMETHOD AS PAYMENT_METHOD,
    STATUS,
    CREATED,
    AMOUNT / 100 AS AMOUNT,
    CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM
    {{ source("stripe", "stripe_payments") }}
